### ISSUE TITLE
Public resolver?

### ISSUE THREAD

**Issue by jedisct1** [ustclug/neatdns#10]
Hi,

And good job on NeatDNS!

I was just wondering if you had a public running DNSCrypt instance (that forwards to servers in mainland China for chinese domains, and servers outside mainland China for non-chinese domains)?

If you do, maybe you can add it to https://github.com/DNSCrypt/dnscrypt-resolvers ?

**Comment by gaoyifan** [comment]
We do serve an official private resolver, which is only for the users in campus. 
I'm sorry, but we do not plan to make it public for legal reasons.
