### ISSUE TITLE
[Usage] DONT support dnscrypt-proxy 2

### ISSUE THREAD

**Issue by honwen** [ustclug/neatdns#11]
client: https://github.com/jedisct1/dnscrypt-proxy

DNS Stamp Generate by https://dnscrypt.info/stamps

dnscrypt:`
sdns://AQcAAAAAAAAAEzIwMi4xNDEuMTYyLjEyMzo0NDMgQ2UVh-egjHwXWdMAYhiJrlmZQspWLssAA-UhR6hQ4ZEbMi5kbnNjcnlwdC1jZXJ0LmV4YW1wbGUub3Jn
`

doh: `sdns://AgcAAAAAAAAADzIwMi4xNDEuMTYyLjEyMwATbmVhdGRucy51c3RjbHVnLm9yZwgvcmVzb2x2ZQ`

All timeout

**Comment by szescxz** [comment]
About DoH, log of dnscrypt-proxy 2 says
[`[ERROR] Webserver returned an unexpected response`](https://github.com/jedisct1/dnscrypt-proxy/blob/0e2d78d21bd0763636fcc8ef52f79a5095d49994/dnscrypt-proxy/serversInfo.go#L324)
So I did a simple test:
```
>>> import requests
>>> data = b'\xca\xfe\x01\x00\x00\x01\x00\x00\x00\x00\x00\x01\x00\x00\x02\x00\x01\x00\x00)\x10\x00\x00\x00\x80\x00\x00\x00'
>>> requests.post("https://%s/resolve" % (domain_of_neatdns), data=data, headers={"Accept": "application/dns-message", "Conte
nt-Type": "application/dns-message"}).text[0] == '\xca'
False
>>> requests.post("https://cloudflare-dns.com/dns-query", data=data, headers={"Accept": "application/dns-message", "Cont
ent-Type": "application/dns-message"}).text[0] == '\xca'
True
```

Hope this helps a bit.
