### ISSUE TITLE
该项目和chinadns相比，解决了什么问题？

### ISSUE THREAD

**Issue by tony1016** [ustclug/neatdns#2]
比起chinadns项目，性能如何？有哪些新的特性？？

**Comment by gaoyifan** [comment]
我没了解过ChinaDNS，官方项目页面也没介绍清楚原理。
能介绍一下吗？ @tony1016

**Comment by tony1016** [comment]
这么说起来，应该和你的工程做的一件事情。国内根据chnroute分流，国外的根据规则把污染过滤掉

**Comment by tony1016** [comment]
话说中科大DNS怎么趴了，全是污染

**Comment by gaoyifan** [comment]
@tony1016  我查了一下，由于未知原因，服务器无法访问8.8.8.8, 8.8.4.4，因此就fallback成递归查询了。
我刚才换了一个线路，先观察一段时间吧

**Comment by ghost** [comment]
找了一下原作者写的说明，也不是很详细。
https://web.archive.org/web/20150213015148/http://www.v2ex.com/t/124550
>同时用 114 和 Google DNS 解析，国内网站无延迟；
对于不包含黑名单 IP 的包，比如 dig txt/cname youtube.com，采取延迟策略，让正确的包先返回，也能解决相应的污染问题

后来有段时间还出现了随机投毒 IP 的事情，原作者上线了新版本，修改了策略。
https://web.archive.org/web/20150105012817/http://v2ex.com/t/158525

**Comment by gaoyifan** [comment]
顺序反过来了哈~
原先中科大DNS是通过隧道解析被污染的域名，现在改成了直接丢弃被污染的包.....
