### ISSUE TITLE
增加几个环境变量吧

### ISSUE THREAD

**Issue by shirakun** [ustclug/neatdns#3]
比如国内外的上游dns服务器,现在我看配置文件里国内用的合肥的,国外用的google的,想换就得从新构建
顺便,看里面有dnscrypt的相关配置,问下dnscrypt的证书哪里设置的
水平渣,看不懂

**Comment by gaoyifan** [comment]
see 73ce0348a5e8705874793bcc38bcf8c65f7cdc48
