### ISSUE TITLE
DNS似乎再次被污染！？

### ISSUE THREAD

**Issue by miaomiaosoft** [ustclug/neatdns#5]
λ  nslookup www.dropbox.com 202.141.162.123
服务器:  lug.ustc.edu.cn
Address:  202.141.162.123

非权威应答:
名称:    www.dropbox.com
Address:  64.13.192.76

λ  nslookup -vc www.dropbox.com 202.141.162.123
服务器:  lug.ustc.edu.cn
Address:  202.141.162.123

非权威应答:
名称:    www.dropbox-dns.com
Addresses:  2620:100:6032:1::a27d:5201
          67.228.102.32
Aliases:  www.dropbox.com

多次NSLOOKUP，发现时常会被污染！

**Comment by gaoyifan** [comment]
感谢报告。 这是由于网关的出国线路配置出错，导致流量被污染了。
目前该问题已修复，请稍后重试。
