### ISSUE TITLE
在树莓派3上面不能正常编译

### ISSUE THREAD

**Issue by asd2003asd** [ustclug/neatdns#8]
在树莓派3上面不能正常编译，上面时候能够适配arm平台？
Sending build context to Docker daemon  45.06kB
Step 1/4 : FROM smartentry/alpine:3.6-0.4.0
 ---> fd6124af5993
Step 2/4 : MAINTAINER Yifan Gao <docker@yfgao.com>
 ---> Using cache
 ---> 46a3ad3d5611
Step 3/4 : ADD .docker $ASSETS_DIR
 ---> Using cache
 ---> f655863d765f
Step 4/4 : RUN smartentry.sh build
 ---> Running in 3ea06503dc34
standard_init_linux.go:190: exec user process caused "exec format error"
The command '/bin/sh -c smartentry.sh build' returned a non-zero code:

**Comment by gaoyifan** [comment]
抱歉，目前没有支持ARM架构的计划。
